#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XiaomiMIUIHellas.Resource", IsApplication=true)]

namespace XiaomiMIUIHellas
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backbutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backroundsea = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int black_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int black_background_edited = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int blackbackground = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int buttonscrolldown = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int discussforum = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int enter = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int forwardbutton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int hellaslogo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int home = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int HomeButtonWhite = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int login = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int loginblack = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int logoHD = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int menubutton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int mi = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int mi3png = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int mifan = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int mimix = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int mimixx = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int MyButtons = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int phones = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int reload = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ReloadButtonWhite = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int RoundedButtons = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int sunsetbackground = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int supportbutton = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int supportred = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int testedited = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int testingbackgroundblured = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int woodsign = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int XiaomiDevices = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int xtrvroms = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int LinearMainLayout = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int ScrollView01 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int VipButton = 2131099651;
			
			// aapt resource value: 0x7f060019
			public const int backpageButton = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int dropdownmenubutton = 2131099656;
			
			// aapt resource value: 0x7f060018
			public const int forwardpageButton = 2131099672;
			
			// aapt resource value: 0x7f06000a
			public const int gridLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int guidesbutton = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int hellasLogoView = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int hiddenLayout = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int homebuttonMiPhones = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int homebuttonWebSite = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int loadingtext = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int miImageButton = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int miphoneswebview = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int refreshbuttonMiPhones = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int refreshbuttonWebSite = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayout1 = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int relativeLayout2 = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int relativeLayoutwebSite = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int textView4 = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int textView5 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textView6 = 2131099654;
			
			// aapt resource value: 0x7f060017
			public const int webSiteView = 2131099671;
			
			// aapt resource value: 0x7f060007
			public const int websitebutton = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int xtrvImageButton = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MiPhones = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int NewMain = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int WebSite = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
